# Generated by Django 4.2 on 2023-05-13 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_customer_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
